### ISSUE TITLE
How to build on Ubuntu 22.04?

### ISSUE THREAD

**Issue by xandark** [tschak909/platoterm-x11#13]
I'm not a n00b to building projects, and there is no mention in the README.md about it. When I do a `make` with gcc version 11.3, I get a ton of warning and note messages and a stop at this:

```
screen.c: In function ‘screen_handle_client_message’:
screen.c:127:9: error: parameter ‘display’ has incomplete type
  127 | Display display;
      |         ^~~~~~~
```

I'm not sure how to fix this.

This appears to be old K&R C style code. Could there at least be silencing of the warnings? It makes building noisy to filter out what is intentional and what is not.

**Comment by tschak909** [comment]
This was deliberately made for ancient workstations, it uses xlib directly, and recent versions of Xlib may need a different type declaration, sorry can't help you there, you'll need to dig.

-Thom

**Comment by tschak909** [comment]
actually, read this ticket: https://github.com/tschak909/platoterm-x11/issues/1

**Comment by xandark** [comment]
Okay, and could this expectation that this is more for ancient workstations be made explicit in the README.md? Because there was nothing that I read that made me think that this wouldn't run on a modern machine.

**Comment by xandark** [comment]
BTW, that fix did the trick, I can compile and create an executable, although still with tons of warnings.

**Comment by polluks** [comment]
> BTW, that fix did the trick, I can compile and create an executable, although still with tons of warnings.

Indeed, 120 warnings generated.

**Comment by xandark** [comment]
I am now compiling this under Garuda Linux (Arch) and I found that the real fix is this:

screen.c line 127:
`Display display;`

change to:
`Display* display;`

`display` happens to be a global variable that is defined as a `Display*` not `Display`, which is why the compiler was complaining, as all references to it have to be a pointer. This only worked because the function doesn't even reference this argument. Anyways, this makes it compile.

**Comment by xandark** [comment]
Also another tip: I added some more "no warn" flags to the Makefile so that it now compiles cleanly, no spamming the console:

from

`CFLAGS=-g -Wno-error=implicit-function-declaration -Wno-error=return-type`

to

`CFLAGS=-g -Wno-error=implicit-function-declaration -Wno-error=return-type -Wno-implicit-int -Wno-implicit-function-declaration -Wno-old-style-definition -Wno-builtin-declaration-mismatch -Wno-return-mismatch`

**Comment by polluks** [comment]
Well, better fix warnings than turning off them.

**Comment by tschak909** [comment]
Thanks. :)
